name: Hello World AMP  
description: This is a simple example of an AMP.
author: Cloudera Education
specification_version: 1.0
prototype_version: 1.0
date: "2024-09-30"

environment_variables:
  RANDOM_VARIABLE_NAME:
    default: "DEFAULT-VALUE"
    description: "This is just an example of how to create an environment variable."
    required: false

runtimes:
  - editor: Workbench ## Other acceptable values are determined by the runtimes available in your CML environment
    kernel: Python 3.10 ## Same here, check your runtimes (custom runtimes can be added as well)
    edition: Standard ## Particularly relevant if using GPUs, Nvidia GPU

## Below are some sample tasks based on some of the most popular aspects of AMP creation.
tasks:

  ## SESSION related AMP snippet
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-dependencies/install-dependencies.py
    short_summary: Install Requirements and Dependencies
    kernel: python3
    cpu: 2
    memory: 4
  
  ## APPLICATION related AMP snippet
  - type: start_application
    name: Simple Web Server
    short_summary: This is a simple web server application.
    long_summary: This is an example of exposing an application using the CDSW_APP_PORT environment variable.
    subdomain: hello-world
    script: 1_app-run-web-server/app.py
    environment_variables:
      TASK_TYPE: START_APPLICATION